name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install

      - name: Prettier lint
        run: yarn prettier --check .

      - name: TypeScript check
        run: yarn tsc

      - name: Jest tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '16.x'
        with:
          name: dist
          path: dist
          retention-days: 7
